language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: hUahjNzfaRHQ3SlFGtgu78c+U5GueRyFWaSgBJYlFC0oSNamAFE8u0Mco6cWv8VcIuhfEs22bDXzIL+UQrl9egFSzG1MoA15LYGcCHhxJ0x7rW91p7YCJG5snYxZ5pL/n6w4pH/h0hfJjsaaB9i+xpu/BSSRSnDuHr+C6kUKHME=
notifications:
  email: false
  slack:
    secure: LFlUmWLokxjpFfqwVNdUus73QZffjLJkjHm/kpCy6OaUgtliB1B8jOMOHDqYT1iz8kD0xXVyWipFwkl++jWADS0Qz+XW0qYYsrCwNoZiWaBXE7e22BzGoZn3lwA467S1KzR2BjAUOZE3mutDttSrcsotAGWjodtvKeGSB2VuJmk=
sudo: false
